name: Pipeline

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: vaulted-scholar-384618
  INSTANCE_NAME: friday
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8"]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r ./api/reqs.txt
  #       pip install pylint
       
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint ./api/app.py ./api/agents.py
      
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
      
    - name: Authenticate with GCP account
      run: |
        echo "$SERVICE_ACCOUNT_KEY" > /tmp/creds.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/creds.json
        ls $GOOGLE_APPLICATION_CREDENTIALS
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

    - name: Deploy app
      run: |

        gcloud compute scp --recurse /home/runner/work/friday/friday mostafa_ramadan1@friday:/home/mostafa_ramadan1/friday --zone us-central1-a
        gcloud compute ssh friday --zone us-central1-a --command 'sudo chmod -R 777 /home/mostafa_ramadan1/friday && cd /home/mostafa_ramadan1/friday/client && npm install'
        gcloud compute ssh friday --zone us-central1-a --command 'cd /home/mostafa_ramadan1/friday/api && pip3 install -r reqs.txt'

    - name: Run app
      run: |
        gcloud compute ssh friday --zone us-central1-a --command 'sudo cd /home/mostafa_ramadan1/friday/api && sudo python3 app.py'
        gcloud compute ssh friday --zone us-central1-a --command 'sudo cd /home/mostafa_ramadan1/friday/client && sudo yarn dev'




# gcloud compute ssh friday --zone us-central1-a --command 'sudo mkdir -p /home/mostafa_ramadan1/friday'
# gcloud compute ssh friday --zone us-central1-a --command 'sudo chmod -R 777 /home/mostafa_ramadan1/friday'